[versions]
# libraries
junit = "4.13.2"
jettyServer = "9.4.56.v20240826"
jna = "5.13.0"
cdt = "5.0.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.0.1"
kotlin = "1.9.25"
kover = "0.8.3"
qodana = "2024.1.9"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
jettyServer = { group = "org.eclipse.jetty", name = "jetty-server", version.ref = "jettyServer" }
jettyServlet = { group = "org.eclipse.jetty", name = "jetty-servlet", version.ref = "jettyServer" }
jnaPlatform = { group = "net.java.dev.jna", name = "jna-platform", version.ref = "jna"}
cdt = { group = "io.github.sskorol", name = "cdt-java-client", version.ref = "cdt"}

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
